### ISSUE TITLE
Menus are hidden by main pane

### ISSUE THREAD

**Issue by philpraxis** [zeek/try-zeek#12]
See attached screenshot when I hover over "Get zeek", "Documentation", ...

<img width="1552" alt="Screenshot 2020-07-07 at 18 56 06" src="https://user-images.githubusercontent.com/47710/86817949-0299b580-c086-11ea-9bc2-bce72c2877d9.png">

**Comment by JustinAzoff** [comment]
Hi!

thanks for mentioning this.  I looked into how the header is working since the site redesign and noticed that I'm really just pulling in a full 404 page into the header.. so the whole thing needs to be re-done in a different way, which should fix that problem.  I'll  probably just re-create a minimal header that just links to zeek.org to avoid having to include all the dropdown menu stuff.

**Comment by JustinAzoff** [comment]
Partially fixed in 4c89aaa8b99f84a37.  Removed the old iframe and just added the logo.  Should be able to recreate most of the menu as well, but just showing the logo might be good enough.

**Comment by JustinAzoff** [comment]
No one seems to have missed the menu,  should be fine to continue to leave it how it is.
