### ISSUE TITLE
Formatting support

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/try-zeek#70]
Now that https://github.com/zeek/zeekscript is a thing it would be nice to have a way to automatically format code.

feat/format is an initial branch with basic support for this.

Some things to decide though:

* Should there even be a format button, or should it just format on run?  I see https://go.dev/play/ has a Format button, but it also Formats on run.  I'm thinking if we do format on run, a dedicated format button is not needed.
* Should format errors be returned.  If we format on run, errors will be returned anyway, and I'm not sure if we can fully rely on zeekscript being 100% in sync with zeek errors anyway.  With a dedicated format button it's a little weird that it returns the original input if there's any errors, but doesn't show the errors.

Other issues:

It's long overdue for the repo to have some automated tests. The challenge is that we mostly need e2e tests as a lot of the issues have been with docker and container stuff.   Mocking everything likely won't be terribly useful.  There's 3 types of things to test:
 
* The HTTP JSON API
* The JS Frontend
* That the JS frontend is in sync with the HTTP API - if we mock the API in the tests, that won't help if the API changes by accident.

Are there any security issues with running zeekscript with untrusted data?

**Comment by bbannier** [comment]
Great to see this.

> Should there even be a format button, or should it just format on run? 

I believe we are still shaking out cases where zeek-format incorrectly changes sources so that e.g., source files become invalid, so I believe there needs to be a way to opt out of formatting.

> Should format errors be returned.

In my experience the tree-sitter parser has been much robust that Zeek's builtin parser, e.g., a missing `;` can completely throw of Zeek's parser while the tree-sitter parser might suggest inserting a `;` close to the right location. For bbannier/zeek-language-server I went with surfacing tree-sitter errors while the documented is being edited but not saved, e.g., given

```zeek
type X: record {
	a: count
};
```

the missing `;` after `count` leads to the tree-sitter parser emitting an error node `missing` at line 3, col 1 (just before the `}`). The location information is used to highlight error ranges. I also use this to offer fixits, in this case insert the missing text at the given location which would lead here to the syntactically correct, but weirdly formatted code

```zeek
type X: record {
	a: count
;};
```

As soon as a document is saved I replace the tree-sitter errors which what comes back from Zeek, in this case `syntax error, at or near "}"` (the error message from Zeek is also on line 3, but misses column information).

try-zeek could follow a similar model where tree-sitter errors are surfaced until a file was run; after that one could use the errors from Zeek.

> Are there any security issues with running zeekscript with untrusted data?

Unlikely directly if one does not use the C-bindings, but instead ones in a high-level language. I have no come across this, but it might be possible to craft input which makes the parser take a long time to finish (I usually see it return results very quicky, O(ms)); since `zeek-format` is implemented it Python it is probably very hard to make it run on the client, so it might make sense to put an upper limit on the time we allow formatting to run on the server.

**Comment by vpax** [comment]
What's the connection between this and `try-zeek`? I'm missing the basic picture.

**Comment by bbannier** [comment]
> What's the connection between this and `try-zeek`? I'm missing the basic picture.

This issue is about adding formatting support to try-zeek snippets via https://github.com/zeek/zeekscript/. That tool uses a full, custom [tree-sitter](https://tree-sitter.github.io/tree-sitter/) [parser](https://github.com/zeek/tree-sitter-zeek) for Zeek's language, and surfaces syntax errors. One of Justin's questions was whether these errors should be surfaced to the user, and I was trying to argue that 1) this would be useful, and 2) doing this while editing would be even better (but would likely require putting this into the Javascript frontend instead of the Python backend.

**Comment by vpax** [comment]
I get the technical end. What I'm unclear on is how does this relate to `try-zeek` in terms of the experience of the users of the site. I'd think they just want to enter their scripts and see what happens. Is this about presenting canned scripts to them?

**Comment by bbannier** [comment]
I believe this assumes that there are users which edit directly in the try-zeek web UI (and don't exclusively paste existing code). Integrating zeek-format into this would give such users a way to "tidy up" their sources before sharing so they are consistently formatted; this is a common feature of playgrounds.

**Comment by JustinAzoff** [comment]
Yeah, a lot of people use try.zeek as their only zeek development environment.

RE: wasm tree-sitter, I've also been wondering how feasible it would be to compile zeek to wasm using emscripten or such and run the whole thing client side.

**Comment by bbannier** [comment]
> RE: wasm tree-sitter, I've also been wondering how feasible it would be to compile zeek to wasm using emscripten or such and run the whole thing client side.

Building a wasm module for the binary might be feasible, but I'd be more worried about the scripts which would need to be distributed to make Zeek do anything meaningful. This would likely require a full vfs module which can provide them to a wasm-built Zeek. This sounds like a lot of work, and I believe such use cases might be better served by tools like https://github.com/bbannier/zeek-playground (be it via GH codespaces or tools like [DevPod](https://devpod.sh/)). Providing a full dev env requires much more than the simple playground try.zeek.org can provide (and neither [ACE](https://github.com/ajaxorg/ace/issues/3124) nor [Monaco](https://microsoft.github.io/monaco-editor/) currently support LSP, so there would be no inline documentation, completion, ...).

**Comment by JustinAzoff** [comment]
Well, It's easy enough to return the errors from zeekscript to the API and show them in the editor like `Run` does.

![image](https://github.com/zeek/try-zeek/assets/65812/615283b1-ec1a-41bd-abee-4a058bd19288)

I'm probably doing something wrong because I ended up needing to parse the return of `get_error()`

(there's an off by one I need to fix)

**Comment by JustinAzoff** [comment]
I deployed the initial version of this on the live site, now that people can poke at it should be able to get some additional feedback.  It's still opt-in and does not format-on-run

**Comment by bbannier** [comment]
Closing as #71 has been merged.
